#!/bin/bash
# https://docs.docker.com/docker-cloud/builds/advanced/

# $IMAGE_NAME var is injected into the build so the tag is correct.
echo "[***] Build hook running"

export $(grep -v '^#' ../.env | xargs)

docker pull $DOCKER_REPO:modules-latest

docker build \
    --build-arg MODULES_TAG=$MODULES_TAG \
    --build-arg PHP_VER=$PHP_VER \
    --build-arg BUILD_RFC3339=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
    --build-arg COMMIT=$(git rev-parse --short HEAD) \
    --build-arg VERSION=$(git describe --tags --always) \
    -t $IMAGE_NAME .
